[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Omite la variable en el escáner de secretos de Netlify
  SECRETS_SCAN_OMIT_KEYS = "GEMINI_API_KEY"

# Redirección para Single Page Application (evita errores 404 al recargar)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
